### ISSUE TITLE
Pls add an abillitie to disable All in

### ISSUE THREAD

**Issue by CloudeLecaw** [Matsuneitor/Roulette#4]
The New All In Button has great option for some of our Events.

![image](https://user-images.githubusercontent.com/12080017/113110640-965c7480-9207-11eb-8701-6eb3335c447f.png)

But for our Main Roulette tables we dont want it.
It there a way to disable the all in for choosen tables?
If not could you add it <3?

**Comment by aematsubara** [comment]
Yes, I'll add more settings for each game soon!

**Comment by aematsubara** [comment]
Added in the next update.
