### ISSUE TITLE
Players can see vanished players

### ISSUE THREAD

**Issue by iBuseWinner** [Matsuneitor/Roulette#5]
If vanished player join the game then other players can see him.
Also they can see him if he leaves game.

**Comment by aematsubara** [comment]
Which plugin are you using for vanishing?

**Comment by iBuseWinner** [comment]
CMI

**Comment by aematsubara** [comment]
Ok, I'll fix it in the next update, so vanished playes can't join the games 👍

**Comment by aematsubara** [comment]
Added in the next update.
