### ISSUE TITLE
placeholder for crupier broken?

### ISSUE THREAD

**Issue by CloudeLecaw** [Matsuneitor/Roulette#8]
The placeholder for croupier seems to be broken (since a long time now allready, just forgot to report this)
![Snag_107d4870](https://user-images.githubusercontent.com/12080017/116946283-05e7d880-ac7a-11eb-9a39-c52a7777de2c.png)

**Comment by aematsubara** [comment]
Which message from messages.yml is?

**Comment by aematsubara** [comment]
Change %Croupier% for %croupier%

**Comment by CloudeLecaw** [comment]
your right ,,,that was my bad XD
thanks <3

**Comment by aematsubara** [comment]
Haha no problem
